version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - .:/dbdata/var/lib/postgresql/data
      - ./docker/init-dbuser.sh:/docker-entrypoint-initdb.d/init-dbuser.sh
    env_file:
      - .env
  app:
    build: .
    command: >
      sh -c 'bin/rails assets:precompile &&
             bin/rails db:create &&
             bin/rails db:migrate &&
             bin/rails s -b 0.0.0.0 -p ${APP_PORT}'
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/hotwire_chat
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true    # byebug hack
    tty: true           # byebug hack
